apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-t1
  namespace: argo
spec:

  project: project-tenants-contentrus
  
  sources:
    - repoURL: https://github.com/Migas77/contentrus.multiTenancy.git
      targetRevision: SCRUM-24-ArgoCD-Setup
      path: infrastructure/umbrella
      helm:
        valueFiles:
        # - $values/infrastructure/umbrella/values.yaml
        - $values/values.yaml
    - repoURL: 'https://github.com/Migas77/contentrus.multiTenancy.argocdHelmCharts.git'
      targetRevision: HEAD
      ref: values

  destination:
    # server from argocd cluster list --grpc-web
    server: https://kubernetes.default.svc
    namespace: t1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true

