version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: contentrus-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management
    container_name: some-rabbit
    hostname: my-rabbit
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI port
    restart: unless-stopped

volumes:
  mysql_data:
