# Allow only intra-namespace traffic
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-same-namespace
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["istio-system"]
    - from:
        - source:
            namespaces: ["{{ .Release.Namespace }}"]
    - from:
        - source:
            namespaces: ["common"]
    - from:
        - source:
            principals:
            - cluster.local/ns/common/sa/istio-ingress        

