apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.notifications.appName }}-service"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.notifications.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.notifications.port }}
  type: ClusterIP