apiVersion: v1
kind: ConfigMap
metadata:
  name: stripe-listen-script
  namespace: control
data:
  start-stripe.sh: |
    #!/bin/sh
    set -e

    echo "Starting stripe listen..."

    stripe listen --api-key "$STRIPE_API_KEY" --forward-to http://billing/webhook > /shared/stripe-output.log 2>&1 &
    STRIPE_PID=$!

    sleep 5

    secret=$(grep -oE 'whsec_[a-zA-Z0-9]+' /shared/stripe-output.log | head -n1)

    if [ -n "$secret" ]; then
      echo "$secret" > /shared/secret.txt
      echo "Webhook secret written to shared volume."
    else
      echo "Failed to detect webhook secret."
    fi

    wait $STRIPE_PID
