apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-secret-write
  namespace: control
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
