apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-secret-write
  namespace: control
subjects:
  - kind: ServiceAccount
    name: default
    namespace: control
roleRef:
  kind: Role
  name: allow-secret-write
  apiGroup: rbac.authorization.k8s.io
