apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hostedsite.appName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.hostedsite.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.hostedsite.appName }}
        mysql-client: "true"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: {{ .Values.hostedsite.appName }}
          image: {{ .Values.hostedsite.image }}
          ports:
            - containerPort: {{ .Values.hostedsite.port }}
          env:
            - name: ConnectionStrings__piranha
              valueFrom:
                secretKeyRef:
                  name: piranha
                  key: connection-string

