apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.hostedsite.appName }}-service"
spec:
  selector:
    app: {{ .Values.hostedsite.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.hostedsite.port }}
  type: ClusterIP
