apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: "{{ .Values.hostedsite.appName }}-{{ .Release.Namespace }}-virtual-svc"
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "www.contentrus.{{ .Values.hostedsite.appName }}.{{ .Release.Namespace }}.com"
  gateways:
  - "{{ .Release.Namespace }}/{{ .Values.hostedsite.appName }}-gateway"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: "{{ .Values.hostedsite.appName }}-service.{{ .Release.Namespace }}.svc.cluster.local"
