apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: tcommon
  name: kiali
spec:
  istio_namespace: istio-system
  deployment:
    namespace: tcommon
  auth:
    strategy: anonymous
  external_services:
    istio:
      url: http://istiod.tcommon.svc.cluster.local:15014
    prometheus:
      url: http://kube-prometheus-stack-prometheus.tcommon.svc.cluster.local:9090
    grafana:
      enabled: true
      url: http://kube-prometheus-stack-grafana.tcommon.svc.cluster.local
      internal_url: http://kube-prometheus-stack-grafana.tcommon.svc.cluster.local
      dashboards:
      - name: "Istio Mesh Dashboard"
      - name: "Istio Service Dashboard"
        variables:
          namespace: "var-namespace"
          service: "var-service"
      - name: "Istio Workload Dashboard"
        variables:
          namespace: "var-namespace"
          workload: "var-workload"
      - name: "Istio Control Plane Dashboard"
      - name: "Istio Performance Dashboard"
      - name: "Istio Ztunnel Dashboard"