apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.deployment-status: |
    url: http://onboarding.control.svc.cluster.local/webhook/deployment-status
    headers:
      - name: Content-Type
        value: application/json

  template.deployment-finished: |
    webhook:
      deployment-status:
        method: POST
        body: |
          {
            "app": "{{.app.metadata.name}}",
            "status": "{{.app.status.sync.status}}",
            "health": "{{.app.status.health.status}}",
            "tenantNamespace": "{{.app.spec.destination.namespace}}",
            "timestamp": "{{now | date "2006-01-02T15:04:05Z07:00"}}"
          }

  trigger.on-deployment-finished: |
    - name: on-deployment-finished
      description: Trigger when app is synced and healthy or unhealthy
      send:
        - deployment-finished
      when: app.status.sync.status == 'Synced' and (app.status.health.status == 'Healthy' or app.status.health.status == 'Unhealthy')

  subscriptions: |
    - recipients:
        - deployment-status
      triggers:
        - on-deployment-finished
