apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: "{{ .Values.hostedsite.appName }}-gateway"
  namespace: {{ .Values.namespace }}
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "www.contentrus.{{ .Values.hostedsite.appName }}.{{ .Values.namespace }}.com"

# https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/
