# Allow only intra-namespace traffic
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-gateway-and-self
  namespace: {{ .Release.Namespace }}
spec:         
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/common/sa/istio-ingress
    - source:
        namespaces:
          - "{{ .Release.Namespace }}"

