# Allow only intra-namespace traffic
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-same-namespace
  namespace: t49acb0d6-d4cb-42de-935a-2f7e2ca5d458
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["t49acb0d6-d4cb-42de-935a-2f7e2ca5d458"]
    - to:
        - operation:
            hosts: ["*.control.svc.cluster.local", "*.common.svc.cluster.local"]
