# Deny everything else
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-cross-namespace
  namespace: {{ .Release.Namespace }}
spec:
  action: DENY
  rules:
    - {}
