apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-only-control
  #use -n to override the tenant namespace
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {} 
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: control
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: argocd
    - from:
        - podSelector: {}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: control
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: common
    - to:
        - podSelector: {}
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53