apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.onboarding.appName }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.onboarding.port }}
  selector:
    app: {{ .Values.onboarding.appName }}