apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    workflows.argoproj.io/description: Deploy Argo Workflow!".
    workflows.argoproj.io/maintainer: '@belchior'
  generateName: deploy-wf
spec:
  
  # This is the entrypoint of the workflow. (the template that will be executed first)
  entrypoint: steps-template
  arguments:
    parameters:
    - name: tenantId
  volumes:
  - name: github-creds-vol
    secret:
      secretName: github-creds
      items:
      - key: ssh-private-key
        path: id_rsa

  templates:
  
  # Template Invocators
  - name: steps-template
    steps:
    - - name: set-tenant-azureblob-credentials
        template: tenant-azureblob-credentials-script
      - name: set-tenant-namespace-and-secrets
        template: tenant-namespace-and-secrets-script
    - - name: trigger-tenant-application-set
        template: tenant-git-commit-script
    
  # Template Definitions
  - name: tenant-azureblob-credentials-script
    script:
      image: python:3.9
      command: [python]
      source: |
        import time
        print("Hello, Argo Workflows!")
        print(time.time())
  
  - name: tenant-namespace-and-secrets-script
    inputs:
      parameters:
      - name: tenantId
        value: "{{workflow.parameters.tenantId}}"
    script:
      image: bitnami/kubectl:1.33.1@sha256:a7413d1c7d19bb4b8d739ee5f9d6b806e94effa180bfd4a221d5874c00821a2c
      command: [bash]
      source: |
        #!/bin/bash
        set -e

        echo "TenantId {{inputs.parameters.tenantId}}..."

        NAMESPACE="t{{inputs.parameters.tenantId}}"

        kubectl create namespace $NAMESPACE || echo "Namespace already exists"

        ROOT_PASSWORD=$(head /dev/urandom | tr -dc 'A-Za-z0-9_' | head -c 24)

        kubectl create secret generic mysql-secrets \
          --from-literal=mysql-root-password=$ROOT_PASSWORD \
          --from-literal=mysql-replication-password=$(head /dev/urandom | tr -dc 'A-Za-z0-9_' | head -c 24) \
          --from-literal=mysql-password=$(head /dev/urandom | tr -dc 'A-Za-z0-9_' | head -c 24) \
          -n $NAMESPACE

        kubectl create secret generic piranha \
          --from-literal=connection-string="Server=$NAMESPACE-mysql;Database=piranha;User=root;Password=$ROOT_PASSWORD;Port=3306" \
          -n $NAMESPACE

        echo "Namespace and secrets successfully configured."
  
  - name: tenant-git-commit-script
    inputs:
      parameters:
      - name: tenantId
        value: "{{workflow.parameters.tenantId}}"
    script:
      image: alpine/git:2.47.1@sha256:ec9ce19e30e68365398ec07a30f744439fcad1bd7cae33122871b868cf2c6cee
      command: [sh]
      volumeMounts:
        - name: github-creds-vol
          mountPath: /root/.ssh/
      source: |
        #!/bin/sh
        set -e

        mkdir /.ssh/
        cp /root/.ssh/id_rsa /.ssh/id_rsa
        chmod 600 /.ssh/id_rsa

        export GIT_SSH_COMMAND="ssh -i /.ssh/id_rsa -o StrictHostKeyChecking=no"

        git clone git@github.com:Migas77/contentrus.multiTenancy.argocdHelmCharts.git

        cd contentrus.multiTenancy.argocdHelmCharts/tenants
        mkdir t{{inputs.parameters.tenantId}}
        cd t{{inputs.parameters.tenantId}}
        touch values.yaml

        git config --add --local user.name "Argo Workflow Bot"
        git config --add --local user.email "bot@argo.pt"

        git add values.yaml
        git status
        git commit -m "Tenant {{inputs.parameters.tenantId}} created"
        git status
        git push origin main

