apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: {{ .Values.namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: simplest-collector
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
