apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: simplest-collector
spec:
  selector:
    app.kubernetes.io/name: simplest-collector
  ports:
    - protocol: TCP
      port: {{ .Values.otelCollector.service.port }}
      targetPort: {{ .Values.otelCollector.service.targetPort }}
      name: prometheus
